"use client";

import { useRef, useState, type KeyboardEvent } from "react";
import {
  ChartScatter,
  ChevronDown,
  Maximize,
  Minus,
  Play,
  Plus,
  SlidersHorizontal,
  Target,
  X,
} from "lucide-react";
import { BandHead } from "./band-parts";
import { MockFrame } from "./mock-frame";

/* Shot map — the dashboard's fullscreen serve-placement viewer (viz-fullscreen
   in the app), ported from the design board's 1280×720 mock.

   The scatter is generated by the same seeded generator the mock uses, so the
   pattern on the landing page is the pattern in the design, point for point.
   Hovering, clicking or focusing a mark swaps the readout to that serve. The
   marks form one tab stop (roving tabindex): Tab lands on the current mark and
   the arrow keys walk the rest, so a keyboard user isn't made to tab through
   fifty-eight serves to leave the section. */

type Outcome = "won" | "lost" | "miss" | "ace";
type Mark = {
  id: string;
  x: number;
  y: number;
  outcome: Outcome;
  lane: string;
  side: string;
  set: string;
  game: number;
};

// Court-group coordinates (pre-zoom), exactly as the design lays them out.
const ZOOM = 1.6;
const PAN_X = -384;
const PAN_Y = -4;

function buildMarks(): Mark[] {
  let seed = 7;
  const rnd = () => {
    seed = (seed * 16807) % 2147483647;
    return (seed - 1) / 2147483646;
  };
  const g = (m: number, s: number) => m + (rnd() + rnd() + rnd() - 1.5) * s;
  const out: Mark[] = [];
  const boxes = [
    { side: "Deuce", l: 544, r: 638 },
    { side: "Ad", l: 642, r: 736 },
  ];
  const lanes: [string, number][] = [
    ["T", 0.1],
    ["Body", 0.5],
    ["Wide", 0.9],
  ];
  const sets = ["Set 1", "Set 2", "Set 3"];
  let n = 0;
  const push = (m: Omit<Mark, "id" | "set" | "game">) => {
    n++;
    out.push({ id: "s" + n, set: sets[n % 3], game: 1 + ((n * 7) % 10), ...m });
  };
  boxes.forEach((b) =>
    lanes.forEach(([lane, t]) => {
      const cnt = lane === "Body" ? 6 : 8;
      for (let i = 0; i < cnt; i++) {
        const x = g(b.l + (b.r - b.l) * t, 16);
        const y = g(222, 34);
        const outcome: Outcome = rnd() < 0.7 ? "won" : "lost";
        push({
          x: Math.max(b.l + 3, Math.min(b.r - 3, x)),
          y: Math.max(202, Math.min(345, y)),
          outcome,
          lane,
          side: b.side,
        });
      }
    }),
  );
  (
    [
      [546, 206, "Wide", "Deuce"],
      [633, 210, "T", "Deuce"],
      [636, 224, "T", "Deuce"],
      [646, 208, "T", "Ad"],
      [731, 214, "Wide", "Ad"],
      [648, 230, "T", "Ad"],
    ] as const
  ).forEach(([x, y, lane, side]) => push({ x, y, outcome: "ace", lane, side }));
  (
    [
      [590, 188],
      [668, 191],
      [712, 186],
      [538, 240],
      [741, 262],
      [612, 345],
      [690, 346],
      [700, 194],
    ] as const
  ).forEach(([x, y]) =>
    push({
      x,
      y,
      outcome: "miss",
      lane: y > 340 ? "Net" : y < 199 ? "Long" : "Wide",
      side: x < 640 ? "Deuce" : "Ad",
    }),
  );
  return out;
}

const MARKS = buildMarks();
const FIRST_ACE = MARKS.find((m) => m.outcome === "ace")!.id;
const FILL: Record<Exclude<Outcome, "ace">, string> = {
  won: "#5DB955",
  lost: "#E51837",
  miss: "#C9CBCE",
};

function star(cx: number, cy: number, R: number) {
  const r = R * 0.45;
  const p: string[] = [];
  for (let i = 0; i < 10; i++) {
    const a = -Math.PI / 2 + (i * Math.PI) / 5;
    const rad = i % 2 ? r : R;
    p.push((cx + rad * Math.cos(a)).toFixed(2) + "," + (cy + rad * Math.sin(a)).toFixed(2));
  }
  return p.join(" ");
}
const MARK_STAR = star(8, 8, 7);
const LEGEND_STAR = star(5, 5, 4.2);

function title(m: Mark) {
  if (m.outcome === "ace") return `Ace · ${m.lane}, ${m.side.toLowerCase()}`;
  if (m.outcome === "miss") return `Fault · ${m.lane}`;
  return `${m.outcome === "won" ? "Point won" : "Point lost"} · ${m.lane}, ${m.side.toLowerCase()}`;
}
const label = (m: Mark) => `${title(m)}, ${m.set.toLowerCase()} game ${m.game}`;

function ShotMapMock() {
  const [activeId, setActiveId] = useState(FIRST_ACE);
  const refs = useRef<(HTMLButtonElement | null)[]>([]);
  const idx = MARKS.findIndex((m) => m.id === activeId);
  const a = MARKS[idx];
  const sx = a.x * ZOOM + PAN_X;
  const sy = a.y * ZOOM + PAN_Y;

  const onKeyDown = (e: KeyboardEvent<HTMLDivElement>) => {
    const step =
      e.key === "ArrowRight" || e.key === "ArrowDown" ? 1 : e.key === "ArrowLeft" || e.key === "ArrowUp" ? -1 : 0;
    if (!step) return;
    e.preventDefault();
    const next = (idx + step + MARKS.length) % MARKS.length;
    setActiveId(MARKS[next].id);
    refs.current[next]?.focus();
  };

  return (
    <div className="shot">
      <div
        className="shot-court"
        role="group"
        aria-label="Serve placement court. Use the arrow keys to move between serves."
        onKeyDown={onKeyDown}
        style={{ transform: `translate(${PAN_X}px, ${PAN_Y}px) scale(${ZOOM})` }}
      >
        <div className="shot-lines" aria-hidden="true">
          <i style={{ left: 510.8, top: 70, width: 258.4, height: 560, background: "#6092CE" }} />
          <i className="box" style={{ left: 510.8, top: 70, width: 258.4, height: 560 }} />
          <i style={{ left: 542, top: 70, width: 2, height: 560 }} />
          <i style={{ left: 736, top: 70, width: 2, height: 560 }} />
          <i style={{ left: 542, top: 198.2, width: 196, height: 2 }} />
          <i style={{ left: 542, top: 499.8, width: 196, height: 2 }} />
          <i style={{ left: 639, top: 198.2, width: 2, height: 303.6 }} />
          <i style={{ left: 639, top: 70, width: 2, height: 8 }} />
          <i style={{ left: 639, top: 622, width: 2, height: 8 }} />
          <i style={{ left: 496, top: 348.5, width: 288, height: 3 }} />
        </div>
        {MARKS.map((m, i) => (
          <button
            key={m.id}
            ref={(el) => {
              refs.current[i] = el;
            }}
            type="button"
            className={`shot-mark ${m.outcome === "ace" ? "is-ace" : "is-dot"}`}
            style={{ left: m.x, top: m.y, background: m.outcome === "ace" ? undefined : FILL[m.outcome] }}
            aria-label={label(m)}
            aria-pressed={m.id === activeId}
            tabIndex={m.id === activeId ? 0 : -1}
            onMouseEnter={() => setActiveId(m.id)}
            onFocus={() => setActiveId(m.id)}
            onClick={() => setActiveId(m.id)}
          >
            {m.outcome === "ace" ? (
              <svg width="11" height="11" viewBox="0 0 16 16" aria-hidden="true">
                <polygon points={MARK_STAR} fill="#F8C84F" stroke="#0D0D0D" strokeWidth="0.6" />
              </svg>
            ) : null}
          </button>
        ))}
      </div>

      {/* Readout for the current serve. aria-live so a screen reader hears the
          selection change as the arrow keys move it. */}
      <span className="shot-ring" style={{ left: sx, top: sy }} aria-hidden="true" />
      <div
        className="shot-readout"
        style={{ left: a.x > 640 ? sx + 24 : sx - 192, top: sy - 30 }}
        aria-live="polite"
      >
        <span className="t">{title(a)}</span>
        <span className="m">
          {a.set} · game {a.game}
        </span>
        <span className="w">
          <Play size={11} strokeWidth={1.8} aria-hidden="true" />
          Watch point
        </span>
      </div>

      {/* Viewer chrome — a picture of the app's controls, not controls. */}
      <div className="shot-score" aria-hidden="true">
        <div className="hd">
          <span className="st">Final</span>
          <span className="flex" />
          <span className="tm">01:42:18</span>
        </div>
        <div className="rows">
          <div className="row">
            <span className="nm is-win">Rudy Quan</span>
            <span className="srv" />
            <span className="flex" />
            <span className="sets">
              <b>6</b>
              <b className="dim">3</b>
              <b>7</b>
            </span>
          </div>
          <div className="row">
            <span className="nm">Federico Gomez</span>
            <span className="flex" />
            <span className="sets">
              <b className="dim">4</b>
              <b>6</b>
              <b className="dim">5</b>
            </span>
          </div>
        </div>
        <div className="ft">
          <span className="av">RQ</span>
          <span className="lb">Serve placement</span>
          <span className="flex" />
          <span className="ct">{MARKS.length} serves</span>
        </div>
      </div>

      <div className="shot-top" aria-hidden="true">
        <span className="pill">
          <SlidersHorizontal size={12} strokeWidth={1.6} />
          All serves<span className="mono">·</span>
          <span className="mono">{MARKS.length}</span>
          <ChevronDown size={12} strokeWidth={1.6} />
        </span>
        <span className="sq">
          <X size={14} strokeWidth={1.6} />
        </span>
      </div>

      <div className="shot-bar" aria-hidden="true">
        <span className="sel">
          <Target size={13} strokeWidth={1.5} />
          Serve placement
          <ChevronDown size={12} strokeWidth={1.5} />
        </span>
        <span className="sel">
          <ChartScatter size={13} strokeWidth={1.5} />
          Scatter
          <ChevronDown size={12} strokeWidth={1.5} />
        </span>
        <span className="flex" />
        <span className="legend">
          <span>
            <i style={{ background: FILL.won }} />
            Point won
          </span>
          <span>
            <i style={{ background: FILL.lost }} />
            Lost
          </span>
          <span>
            <i style={{ background: FILL.miss }} />
            Miss
          </span>
          <span>
            <svg width="10" height="10" viewBox="0 0 10 10">
              <polygon points={LEGEND_STAR} fill="#F8C84F" stroke="#0D0D0D" strokeWidth="0.5" />
            </svg>
            Ace
          </span>
        </span>
        <span className="div" />
        <span className="zb">
          <Minus size={15} strokeWidth={1.7} />
        </span>
        <span className="zv">160%</span>
        <span className="zb">
          <Plus size={15} strokeWidth={1.7} />
        </span>
        <span className="zb">
          <Maximize size={14} strokeWidth={1.6} />
        </span>
      </div>
    </div>
  );
}

export function ShotMap() {
  return (
    <section className="band alt" id="shots">
      <div className="wrap">
        <BandHead
          eyebrow="Shot map"
          title="Every serve, on one court."
          aside="Open any chart fullscreen. Filter by set, side or outcome, then pick a mark to watch that point."
        />
        <MockFrame className="is-shot">
          <ShotMapMock />
        </MockFrame>
      </div>
    </section>
  );
}
